function createfigure(xdata1, ydata1, zdata1)
%CREATEFIGURE(XDATA1,YDATA1,ZDATA1)
%  XDATA1:  contour x
%  YDATA1:  contour y
%  ZDATA1:  contour z

%  Auto-generated by MATLAB on 09-Feb-2017 14:39:47

% Create figure
figure1 = figure('NumberTitle','off','Name','Contour Plot',...
    'InvertHardcopy','off',...
    'Color',[1 1 1]);

% Create axes
axes1 = axes('Parent',figure1,'Layer','top','FontSize',14);
% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes1,[0 1]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes1,[0 1]);
% Uncomment the following line to preserve the Z-limits of the axes
% zlim(axes1,[-1 1]);
box(axes1,'on');
hold(axes1,'all');

% Create contour
contour(xdata1,ydata1,zdata1,'LineColor',[0 0 0],'Fill','on','Parent',axes1);

% Create xlabel
xlabel('X','FontWeight','bold','FontSize',14);

% Create ylabel
ylabel('Y','FontSize',14);

% Create title
title('Contour of \phi','FontWeight','bold','FontSize',16);

% Create colorbar
colorbar('peer',axes1,'SouthOutside','FontSize',14);

